[env:esp32dev]
platform    = espressif32@5.3.0
board       = esp32dev
framework   = arduino

lib_deps =
    https://github.com/mobizt/Firebase-ESP-Client.git
    https://github.com/adafruit/Adafruit_LiquidCrystal.git
    miguelbalboa/MFRC522@^1.4.11

monitor_speed = 115200